export const Ciudades = [
  { value: "Buenos Aires", label: "Buenos Aires" },
  { value: "La Plata", label: "La Plata" },
  { value: "Mar del Plata", label: "Mar del Plata" },
  { value: "Bahía Blanca", label: "Bahía Blanca" },
  { value: "Tandil", label: "Tandil" },
  { value: "Olavarría", label: "Olavarría" },
  { value: "Pergamino", label: "Pergamino" },
  { value: "San Nicolás de los Arroyos", label: "San Nicolás de los Arroyos" },
  { value: "Campana", label: "Campana" },
  { value: "Zárate", label: "Zárate" },
  { value: "CABA", label: "Ciudad Autónoma de Buenos Aires (CABA)" },
  {
    value: "San Fernando del Valle de Catamarca",
    label: "San Fernando del Valle de Catamarca",
  },
  { value: "Andalgalá", label: "Andalgalá" },
  { value: "Belén", label: "Belén" },
  { value: "Santa María", label: "Santa María" },
  { value: "Resistencia", label: "Resistencia" },
  {
    value: "Presidencia Roque Sáenz Peña",
    label: "Presidencia Roque Sáenz Peña",
  },
  { value: "Villa Ángela", label: "Villa Ángela" },
  { value: "Barranqueras", label: "Barranqueras" },
  { value: "Rawson", label: "Rawson" },
  { value: "Comodoro Rivadavia", label: "Comodoro Rivadavia" },
  { value: "Trelew", label: "Trelew" },
  { value: "Puerto Madryn", label: "Puerto Madryn" },
  { value: "Esquel", label: "Esquel" },
  { value: "Córdoba", label: "Córdoba" },
  { value: "Villa María", label: "Villa María" },
  { value: "Río Cuarto", label: "Río Cuarto" },
  { value: "San Francisco", label: "San Francisco" },
  { value: "Carlos Paz", label: "Carlos Paz" },
  { value: "Corrientes", label: "Corrientes" },
  { value: "Goya", label: "Goya" },
  { value: "Paso de los Libres", label: "Paso de los Libres" },
  { value: "Mercedes", label: "Mercedes" },
  { value: "Paraná", label: "Paraná" },
  { value: "Concordia", label: "Concordia" },
  { value: "Gualeguaychú", label: "Gualeguaychú" },
  { value: "Concepción del Uruguay", label: "Concepción del Uruguay" },
  { value: "Formosa", label: "Formosa" },
  { value: "Clorinda", label: "Clorinda" },
  { value: "Pirané", label: "Pirané" },
  { value: "San Salvador de Jujuy", label: "San Salvador de Jujuy" },
  { value: "Palpalá", label: "Palpalá" },
  {
    value: "Libertador General San Martín",
    label: "Libertador General San Martín",
  },
  { value: "Santa Rosa", label: "Santa Rosa" },
  { value: "General Pico", label: "General Pico" },
  { value: "La Rioja", label: "La Rioja" },
  { value: "Chilecito", label: "Chilecito" },
  { value: "Mendoza", label: "Mendoza" },
  { value: "San Rafael", label: "San Rafael" },
  { value: "Godoy Cruz", label: "Godoy Cruz" },
  { value: "Luján de Cuyo", label: "Luján de Cuyo" },
  { value: "Posadas", label: "Posadas" },
  { value: "Oberá", label: "Oberá" },
  { value: "Eldorado", label: "Eldorado" },
  { value: "Neuquén", label: "Neuquén" },
  { value: "San Martín de los Andes", label: "San Martín de los Andes" },
  { value: "Cutral Có", label: "Cutral Có" },
  { value: "Viedma", label: "Viedma" },
  { value: "Bariloche", label: "Bariloche" },
  { value: "Cipolletti", label: "Cipolletti" },
  { value: "Salta", label: "Salta" },
  { value: "Tartagal", label: "Tartagal" },
  { value: "Orán", label: "Orán" },
  { value: "San Juan", label: "San Juan" },
  { value: "Rawson (SJ)", label: "Rawson (SJ)" },
  { value: "Pocito", label: "Pocito" },
  { value: "San Luis", label: "San Luis" },
  { value: "Villa Mercedes", label: "Villa Mercedes" },
  { value: "Río Gallegos", label: "Río Gallegos" },
  { value: "Caleta Olivia", label: "Caleta Olivia" },
  { value: "Santa Fe", label: "Santa Fe" },
  { value: "Rosario", label: "Rosario" },
  { value: "Rafaela", label: "Rafaela" },
  { value: "Venado Tuerto", label: "Venado Tuerto" },
  { value: "Santiago del Estero", label: "Santiago del Estero" },
  { value: "La Banda", label: "La Banda" },
  { value: "Ushuaia", label: "Ushuaia" },
  { value: "Río Grande", label: "Río Grande" },
  { value: "San Miguel de Tucumán", label: "San Miguel de Tucumán" },
  { value: "Tafí Viejo", label: "Tafí Viejo" },
  { value: "Concepción", label: "Concepción" },
];
